config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "programs#landing"

  get 'list', to: 'programs#list'
  get '/teachers', to: 'programs#teachers'
  get '/profile', to: 'programs#profile'

  resources :tracks, only: [:show]

  #teachers:
  get 'michael-jordan-laskey', to: 'programs#michaeljordanlaskey'
  get 'gen-jordan-laskey', to: 'programs#genjordanlaskey'
  get 'collen-mayer', to: 'programs#collenmayer'
  get 'paul-mitchell', to: 'programs#paulmitchell'
  get 'aimee-shelide-mayer', to: 'programs#aimeeshelidemayer'
  get 'casey-stanton', to: 'programs#caseystanton'

  #programs:
  get 'the-way-of-all-the-earth', to: 'programs#thewayofalltheearth'
  get 'to-bless-the-space-between-us', to: 'programs#toblessthespacebetweenus'

  #stripe:
  post '/webhook', to: 'stripe#webhook'

  resources :charges

  post 'monthly_subscription', to: 'charges#monthly_subscription_create'
  post 'yearly_subscription', to: 'charges#yearly_subscription_create'
  post 'forever_subscription', to: 'charges#forever_subscription_create'

  #development:
  get 'logout_link', to: 'programs#logout_link'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord

  belongs_to :teacher
  has_many :tracks


end

app/models/teacher.rb
class Teacher < ApplicationRecord

  has_many :programs

end

app/models/track.rb
class Track < ApplicationRecord

  belongs_to :program

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def access

    stripe_subscription_status =
      Stripe::Customer.retrieve(self.stripe_customer_id).subscriptions.data[0].status

    if self.access_forever == true
      true
    elsif stripe_subscription_status == 'active' || stripe_subscription_status == 'trialing'
      true
    else
      false
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def monthly_subscription_create

    if current_user.stripe_customer_id == nil

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      current_user.stripe_customer_id = customer.id
      current_user.save

    end

    subscription = Stripe::Subscription.create(
      :customer => current_user.stripe_customer_id,
      :plan => "0001"
    )

    if subscription
      #Mailer
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def yearly_subscription_create

    if current_user.stripe_customer_id == nil

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      current_user.stripe_customer_id = customer.id
      current_user.save

    end

    Stripe::Subscription.create(
      :customer => current_user.stripe_customer_id,
      :plan => "0002"
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def forever_subscription_create

    if current_user.stripe_customer_id == nil

      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )

      current_user.stripe_customer_id = customer.id
      current_user.save

    end

    charge = Stripe::Charge.create(
      :customer    => current_user.stripe_customer_id,
      :amount      => 19999,
      :description => 'Rails Stripe customer FOREVER',
      :currency    => 'usd'
    )

    if charge
      current_user.access_forever = true
      current_user.save
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  before_action :authenticate_user!, :except => [:landing]

  def index
  	@programs = Program.all
  	@tracks = Track.all
  end

  def test
  end

  def logout_link
  end

  def list
    @recommended_programs = Program.take(5)
    @sacramental_prep_programs = Program.take(8)
    @all_programs = Program.all
    @access = current_user.access
  end

  def landing
  end

  def teachers
    @teachers = Teacher.all.order(:last_name)
  end

  def profile
    @user = current_user
  end

  def teacher
    @teacher = Teacher.first
    @programs = Program.take(10)
  end

  def michaeljordanlaskey
    @access = current_user.access
    @teacher = Teacher.first
    @programs = Program.take(4)
    @programs_hashes = []

    @programs.each do |program|
      @program_hash = {
        title: program.title,
        num_program_tracks: program.tracks.count,
        premium: program.premium,
        pic_link: program.pic_link,
        id: program.id
      }
      @programs_hashes << @program_hash
    end
  end

  def genjordanlaskey
    @access = current_user.access
    @teacher = Teacher.find_by(first_name: 'Gen')
    @programs = Program.take(4)
    @programs_hashes = []

    @programs.each do |program|
      @program_hash = {
        title: program.title,
        num_program_tracks: program.tracks.count,
        premium: program.premium,
        id: program.id
      }
      @programs_hashes << @program_hash
    end
  end

  def collenmayer
    @access = current_user.access
    @teacher = Teacher.find_by(first_name: 'Collen')
    @programs = Program.take(4)
    @programs_hashes = []

    @programs.each do |program|
      @program_hash = {
        title: program.title,
        num_program_tracks: program.tracks.count,
        premium: program.premium,
        id: program.id
      }
      @programs_hashes << @program_hash
    end
  end

  def paulmitchell
    @access = current_user.access
    @teacher = Teacher.find_by(first_name: 'Paul')
    @programs = Program.take(4)
    @programs_hashes = []

    @programs.each do |program|
      @program_hash = {
        title: program.title,
        num_program_tracks: program.tracks.count,
        premium: program.premium,
        id: program.id
      }
      @programs_hashes << @program_hash
    end
  end

  def aimeeshelidemayer
    @access = current_user.access
    @teacher = Teacher.find_by(first_name: 'Aimee')
    @programs = Program.take(4)
    @programs_hashes = []

    @programs.each do |program|
      @program_hash = {
        title: program.title,
        num_program_tracks: program.tracks.count,
        premium: program.premium,
        id: program.id
      }
      @programs_hashes << @program_hash
    end
  end

  def caseystanton
    @access = current_user.access
    @teacher = Teacher.find_by(first_name: 'Casey')
    @programs = @teacher.programs
    @programs_hashes = []

    @programs.each do |program|
      @program_hash = {
        title: program.title,
        num_program_tracks: program.tracks.count,
        premium: program.premium,
        pic_link: program.pic_link,
        id: program.id
      }
      @programs_hashes << @program_hash
    end
  end

  def thewayofalltheearth
    @teacher = Teacher.first
    @program = Program.first
    @tracks = @program.tracks
  end

  def toblessthespacebetweenus
    @teacher = Teacher.find_by(first_name: 'Casey')
    @program = Program.find_by(title: 'To Bless The Space Between Us')
    @tracks = @program.tracks
  end

end

app/controllers/stripe_controller.rb
class StripeController < ApplicationController

  protect_from_forgery :except => :webhook

  def webhook

    # if request.headers['Content-Type'] == 'application/json'
    #   data = JSON.parse(request.body.read)
    # else
    #   # application/x-www-form-urlencoded
    #   data = params.as_json
    # end

    Notification.create(name: params[:type],
                        stripe_id: params[:type],
                        customer_id: params[:type])



    # event_json = JSON.parse(request.body.read)

    # # Do something with event_json

    # status 200


    # # Capture the event information from the webhook params
    # event_id = params[:event]

    # # Verify that the event isn't forged to your Stripe account
    # event = Stripe::Event.retrieve(event_id)

    # render status: 200
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :authenticate_user!

  def show
  	@track = Track.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/forever_subscription_create.html.erb
<h2>Thanks, you <strong>signed up for the FOREVER subscription</strong>!</h2>

app/views/charges/monthly_subscription_create.html.erb
<h2>Thanks, you <strong>signed up for the monthly subscription</strong>!</h2>

app/views/charges/yearly_subscription_create.html.erb
<h2>Thanks, you <strong>signed up for the yearly subscription</strong>!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Il</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="turbolinks-cache-control" content="no-cache">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/programs/aimeeshelidemayer.html.erb
<div class='teacher-container'>

  <%= render "shared/header" %>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { access: @access, teacher: @teacher, programs_hashes: @programs_hashes } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

  <%= react_component 'FooterA' %>

</div> <%# teacher-container %>

app/views/programs/caseystanton.html.erb
<div class='teacher-container'>

  <%= render "shared/header" %>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { access: @access, teacher: @teacher, programs_hashes: @programs_hashes } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

  <%= react_component 'FooterA' %>

</div> <%# teacher-container %>

app/views/programs/collenmayer.html.erb
<div class='teacher-container'>

  <%= render "shared/header" %>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { access: @access, teacher: @teacher, programs_hashes: @programs_hashes } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

  <%= react_component 'FooterA' %>

</div> <%# teacher-container %>

app/views/programs/genjordanlaskey.html.erb
<div class='teacher-container'>

  <%= render "shared/header" %>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { access: @access, teacher: @teacher, programs_hashes: @programs_hashes } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

  <%= react_component 'FooterA' %>

</div> <%# teacher-container %>

app/views/programs/landing.html.erb
<%= render "shared/header" %>

<section class="landing-main">

</section>

<section id="promos" class="section-promos">
  <ul>
    <li id="promo-1"><a href="/list"><h2 class='promo-text'>PROGRAMS</h2></a></li>
    <li id="promo-2"><a href="/teachers"><h2 class='promo-text'>TEACHERS</h2></a></li>
    <li id="promo-3"><a href=""><h2 class='promo-text'>BLOG</h2></a></li>
    <li id="promo-4"><a href=""><h2 class='promo-text'>PODCAST</h2></a></li>
  </ul>
</section>

<%= react_component 'FooterA' %>

app/views/programs/list.html.erb
<div class='program-container'>

  <%= render "shared/header" %>

  <section class='list-background'>

    <section style='min-height: 100%;'>

      <section style='display: flex; flex-direction: row; padding-top: 16px; justify-content: center; position: relative;'>

        <section style='position: relative;'>

          <%= react_component 'CategoryBox', { programs: @recommended_programs, access: @access, title: 'Recommended For You'} %>

          <%= react_component 'CategoryBox', { programs: @sacramental_prep_programs, access: @access, title: 'Sacramental Preparation'} %>

          <%= react_component 'CategoryBox', { programs: @all_programs, access: @access, title: 'All Programs'} %>

        </section>

      </section>

    </section>

  </section>

</div>

app/views/programs/logout_link.html.erb
<a rel="nofollow" data-method="delete" href="/users/sign_out">log out</a>

app/views/programs/michaeljordanlaskey.html.erb
<div class='teacher-container'>

  <%= render "shared/header" %>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { access: @access, teacher: @teacher, programs_hashes: @programs_hashes } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

  <%= react_component 'FooterA' %>

</div> <%# teacher-container %>

app/views/programs/paulmitchell.html.erb
<div class='teacher-container'>

  <%= render "shared/header" %>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { access: @access, teacher: @teacher, programs_hashes: @programs_hashes } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

  <%= react_component 'FooterA' %>

</div> <%# teacher-container %>

app/views/programs/profile.html.erb
<div class='program-container'>

  <%= render "shared/header" %>

  <section class='list-background'>

    <section style='min-height: 100%;'>

      <section style='margin: 16px auto 0px; position: relative; max-width: 720px; padding-left: 16px; padding-right: 16px;'>

        <section style="border: 1px solid rgb(41, 51, 67); border-radius: 5px; background-color: rgb(28, 34, 46); max-width: 720px; width: 100%; align-items: center; padding: 32px; box-sizing: border-box; margin-top: 16px;">
          <section style="font-size: 20px; font-weight: 300; margin-bottom: 16px; color: white;">Subscribe Now!</section>
          <section>
            <section style="font-size: 18px; font-weight: 300; opacity: 0.7; margin-top: 8px; margin-bottom: 8px; color: white">For full access to the Inner Life library, subscribe now! Listen to meditations from the best teachers.</section>
          </section>
          <section style="display: flex; width: 100%; flex-flow: row wrap; justify-content: space-between; align-items: center; margin-top: 16px;">
            <section style="font-size: 16px; text-align: center; margin: 0px; padding: 0px;">
              <section style="position: relative; overflow: hidden; width: 200px; height: 200px; padding: 0px; margin: 0px 8px; display: flex; flex-direction: column; align-items: center; justify-content: space-between; border-radius: 5px; box-sizing: border-box; cursor: pointer; background-color: rgb(52, 169, 180);">
                <section style="padding: 24px 16px 16px;">
                  <section style="font-size: 18px; font-weight: 300; text-align: center; text-transform: none;">Monthly</section>
                  <section style="font-size: 43px; font-weight: 500;">$9.99</section>
                  <section style="font-size: 16px; font-weight: 300; font-style: oblique; text-transform: none;">per month</section>
                </section>

                <%= form_tag(monthly_subscription_path, {:class => 'subscribe-button'})  do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="A month's subscription"
                          data-amount="999"
                          data-image="https://static1.squarespace.com/static/54a21923e4b0be677c12a827/t/54eb76f9e4b0e3df8c199467/1493842069831/?format=1500w"
                          data-locale="auto"
                          data-email="<%=current_user.email%>">
                  </script>

                  <button type="submit" style="position: absolute; left: 0px; bottom: 0px; width: 100%; height: 56px; background-color: rgb(255, 139, 139); font-size: 18px; font-weight: 300; text-transform: none; border: none; font-family: Avenir,Helvetica Neue,Helvetica,Arial,sans-serif;">Subscribe</button>
                <% end %>

              </section>
            </section>
            <section style="font-size: 16px; text-align: center; margin: 0px; padding: 0px;">
              <section style="position: relative; overflow: hidden; width: 200px; height: 200px; padding: 0px; margin: 0px 8px; display: flex; flex-direction: column; align-items: center; justify-content: space-between; border-radius: 5px; box-sizing: border-box; cursor: pointer; background-color: rgb(32, 189, 195);">
                <section style="font-size: 14px; font-weight: 500; display: flex; align-items: center; justify-content: center; position: absolute; height: 20px; width: 120px; top: 25px; right: -46px; padding: 2px 24px; background-color: rgb(255, 139, 139); transform: rotate(45deg);">Most popular!</section>
                <section style="padding: 24px 16px 16px;">
                  <section style="font-size: 18px; font-weight: 300; text-align: center; text-transform: none;">Yearly</section>
                  <section style="font-size: 43px; font-weight: 500;">$8.25</section>
                  <section style="font-size: 16px; font-weight: 300; font-style: oblique; text-transform: none;">per month
                  </section>
                </section>

                <%= form_tag(yearly_subscription_path, {:class => 'subscribe-button'})  do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="A year's subscription"
                          data-amount="9999"
                          data-image="https://static1.squarespace.com/static/54a21923e4b0be677c12a827/t/54eb76f9e4b0e3df8c199467/1493842069831/?format=1500w"
                          data-locale="auto"
                          data-email="<%=current_user.email%>">
                  </script>

                  <button type="submit" style="position: absolute; left: 0px; bottom: 0px; width: 100%; height: 56px; background-color: rgb(255, 139, 139); font-size: 18px; font-weight: 300; text-transform: none; border: none; font-family: Avenir,Helvetica Neue,Helvetica,Arial,sans-serif;">Subscribe</button>
                <% end %>

              </section>
            </section>
            <section style="font-size: 16px; text-align: center; margin: 0px; padding: 0px;">
              <section style="position: relative; overflow: hidden; width: 200px; height: 200px; padding: 0px; margin: 0px 8px; display: flex; flex-direction: column; align-items: center; justify-content: space-between; border-radius: 5px; box-sizing: border-box; cursor: pointer; background-color: rgb(32, 189, 195);">
                <section style="padding: 24px 16px 16px;">
                  <section style="font-size: 18px; font-weight: 300; text-align: center; text-transform: none;">Lifetime</section>
                  <section style="font-size: 43px; font-weight: 500;">$199</section>
                  <section style="font-size: 16px; font-weight: 300; font-style: oblique; text-transform: none;">pay just once!</section>
                </section>

                <%= form_tag(forever_subscription_path, {:class => 'subscribe-button'})  do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="A permanent subscription"
                          data-amount="19900"
                          data-image="https://static1.squarespace.com/static/54a21923e4b0be677c12a827/t/54eb76f9e4b0e3df8c199467/1493842069831/?format=1500w"
                          data-locale="auto"
                          data-email="<%=current_user.email%>">
                  </script>

                  <button type="submit" style="position: absolute; left: 0px; bottom: 0px; width: 100%; height: 56px; background-color: rgb(255, 139, 139); font-size: 18px; font-weight: 300; text-transform: none; border: none; font-family: Avenir,Helvetica Neue,Helvetica,Arial,sans-serif;">Subscribe</button>
                <% end %>

              </section>
            </section>
          </section>
        </section>

      </section>

    </section>

  </section>

</div>

app/views/programs/teacher.html.erb
<div class='teacher-container'>

  <section class='teacher-padding-box'>

    <section class='teacher-box-container'>

      <%= react_component 'TeacherBox', { teacher: @teacher } %>

      <%= react_component 'ProgramsBox', { teacher: @teacher, programs: @programs } %>

    </section> <%# teacher-box-container %>

  </section> <%# teacher-padding-box %>

</div> <%# teacher-container %>

app/views/programs/teachers.html.erb
<div class="teachers-container">

<%= render "shared/header" %>

<section class="teachers-padding-box">

  <section class="teachers-centering-box">

    <section class="teachers-info-box">
      <section class="teachers-text">
        In a cave in the woods, in his deep dark lair,
        through the long cold winter, sleeps a great brown bear
      </section>
    </section><%# teachers-info-box %>

    <section class="teachers-info-box">

      <section class="teachers-text teachers-margin">
        <%= react_component 'TeacherPicLinks', { teachers: @teachers } %>

      </section>

    </section>

  </section>

</section>

<%= react_component 'FooterA' %>

</div>

app/views/programs/thewayofalltheearth.html.erb
<div class='program-container'>

  <%= render "shared/header" %>

  <section class='program-background'>
    <section class='program-background-film'>
    </section>
  </section>

  <section class='program-box-container'>
    <section class='program-box'>

      <%= react_component 'ProgramInfoBox', { program: @program, teacher: @teacher} %>

      <section style="width: 100%; border-bottom: 1px solid rgb(55, 63, 78); margin-bottom: 48px;">
        <section style="transform: translateY(50%); max-width: 220px; margin: 0px auto;">
          <button style="display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 100; font-family: &quot;Avenir Book&quot;, Avenir, Helvetica, Arial, sans-serif; border-width: 0px; border-radius: 2px; padding: 8px; width: 100%; cursor: pointer; background-color: rgb(63, 192, 199); color: rgb(255, 255, 255);">
            <section style="width: 100%;">
              <section style="margin: 0px auto;">
                <section style="display: flex; align-items: center; justify-content: center;">
                  <img src="/assets/play-arrow-2x.png" style="width: 24px; height: 24px; margin-left: -2px;">
                  <section style="font-size: 14px; font-weight: 200;">Begin</section>
                </section>
              </section>
            </section>
          </button>
        </section>
      </section>

      <section class='adventures-box'>
        <section class='adventures-box-title'>
          ADVENTURES
        </section>

        <%= react_component 'AdventuresList', { adventures: @tracks} %>

      </section>

    </section>
  </section>

</div>

app/views/programs/toblessthespacebetweenus.html.erb
<div class='program-container'>

  <%= render "shared/header" %>

  <section class='program-background'>
    <section class='program-background-film'>
    </section>
  </section>

  <section class='program-box-container'>
    <section class='program-box'>

      <%= react_component 'ProgramInfoBox', { program: @program, teacher: @teacher} %>

      <section style="width: 100%; border-bottom: 1px solid rgb(55, 63, 78); margin-bottom: 48px;">
        <section style="transform: translateY(50%); max-width: 220px; margin: 0px auto;">
          <button style="display: flex; align-items: center; justify-content: center; font-size: 12px; font-weight: 100; font-family: &quot;Avenir Book&quot;, Avenir, Helvetica, Arial, sans-serif; border-width: 0px; border-radius: 2px; padding: 8px; width: 100%; cursor: pointer; background-color: rgb(63, 192, 199); color: rgb(255, 255, 255);">
            <section style="width: 100%;">
              <section style="margin: 0px auto;">
                <section style="display: flex; align-items: center; justify-content: center;">
                  <img src="/assets/play-arrow-2x.png" style="width: 24px; height: 24px; margin-left: -2px;">
                  <section style="font-size: 14px; font-weight: 200;">Begin</section>
                </section>
              </section>
            </section>
          </button>
        </section>
      </section>

      <section class='adventures-box'>
        <section class='adventures-box-title'>
          Sessions
        </section>

        <%= react_component 'AdventuresList', { adventures: @tracks} %>

      </section>

    </section>
  </section>

</div>

app/views/shared/_header.html.erb
<section style="position: fixed; top: 0px; height: 54px; width: 100vw; background-color: rgb(41, 51, 67); z-index: 8; box-shadow: rgb(0, 0, 0) 1px 1px 1px;">
  <section style="position: relative; height: 54px; display: flex; flex-direction: row; align-items: center; justify-content: space-between; padding-left: 48px; padding-right: 48px;">
    <section style="display: flex; flex-direction: row; align-items: center; width: 100%; padding-left: 48px; padding-right: 48px; justify-content: space-between; box-sizing: border-box;">
      <section>
        <a href="/" style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-width: 80px;">
          <section style="display: flex; flex-direction: row; align-items: center;">
            <section style="font-size: 18px; font-weight: 200; display: flex; justify-content: center;">
              INNER LIFE
            </section>
          </section>
        </a>
      </section>
    </section>
    <section style="display: flex; flex-direction: row; align-items: center; width: 100%; max-width: 420px; height: 100%; padding-left: 48px; padding-right: 48px; justify-content: space-between; box-sizing: border-box;">
      <section style="flex: 1 1 0%;">
        <a href="/list" style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-width: 80px;">
          <section style="display: flex; flex-direction: row; align-items: center;">
            <img src="https://www.simplehabit.com/static/icon-explore-inactive.svg" style="height: 24px;">
            <section style="font-size: 14px; font-weight: 200; display: flex; justify-content: center;">
            </section>
          </section>
          <section style="margin-top: 2px; font-size: 10px; font-weight: 500; text-transform: uppercase; color: rgb(146, 146, 146);">Explore</section>
        </a>
      </section>

      <section style="flex: 1 1 0%;"><a href="/teachers" style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-width: 80px;">
        <section style="display: flex; flex-direction: row; align-items: center;">
          <img src="https://www.simplehabit.com/static/icon-social-inactive.svg" style="height: 24px;">
          <section style="font-size: 14px; font-weight: 200; display: flex; justify-content: center;">
        </section>
      </section>
      <section style="margin-top: 2px; font-size: 10px; font-weight: 500; text-transform: uppercase; color: rgb(146, 146, 146);">Teachers</section>
    </a>
  </section>
  <section style="flex: 1 1 0%;">
    <a href="/profile" style="display: flex; flex-direction: column; align-items: center; justify-content: center; min-width: 80px;">
      <section style="display: flex; flex-direction: row; align-items: center;">
        <img src="https://www.simplehabit.com/static/default-profile.png" style="height: 20px; width: 20px; border-radius: 50%; border: 2px solid rgb(146, 146, 146);">
        <section style="font-size: 14px; font-weight: 200; display: flex; justify-content: center;">
        </section>
      </section>
      <section style="margin-top: 2px; font-size: 10px; font-weight: 500; text-transform: uppercase; color: rgb(146, 146, 146);">Profile</section>
    </a>
  </section>
</section>
</section>
</section>

app/views/tracks/show.html.erb
<%= react_component 'AudioInterface', {track: @track} %>